site_name: pypi-project-template
site_description: Quickly creating a new Modern Python project and publishing it to PyPI ✨
site_url:

theme:
  features:
    - header.autohide
  name: 'material'
  palette:
    - scheme: default
      primary: amber
      accent: orange
      toggle:
          icon: material/lightbulb
          name: Switch to dark mode
    - scheme: slate
      primary: amber
      accent: orange
      toggle:
          icon: material/lightbulb-outline
          name: Switch to light mode
  favicon: favicon.png
  features:
  - search.suggest
  - search.highlight
  - content.tabs.link
  icon:
    repo: fontawesome/brands/github-alt
    logo: fontawesome/solid/database
repo_name: Yezz123/pypi-project-template
repo_url: https://github.com/yezz123/pypi-project-template
edit_uri: ""

markdown_extensions:
  - markdown_include.include:
      base_path: docs
  - toc:
      permalink: true
  - admonition
  - codehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.tasklist
  - pymdownx.tabbed

plugins:
  - search
  - mermaid2:
      arguments:
        theme: |
          ^(JSON.parse(window.localStorage.getItem('/.__palette')).index == 1) ? 'dark' : 'light'
extra_javascript:
    - https://unpkg.com/mermaid/dist/mermaid.min.js

nav:
  - About: index.md
  - Code of Conduct: code_of_conduct.md
  - License: license.md

extra:
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/yezz123
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/THyasser1
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/in/yezz123
  - icon: fontawesome/solid/globe
    link: https://yezz.me
