name: Build Docs
on:
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-18.04
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/cache@v3
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}-docs
      - name: Install docs extras
        if: steps.cache.outputs.cache-hit != 'true'
        run: pip install -e .[docs]
      - name: Build docs
        run: mkdocs build -d build

      # TODO: Use this to deploy to Netlify
      # - name: Deploy docs
      #   uses: jsmrcaga/action-netlify-deploy@v1.1.0
      #   with:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      #     NETLIFY_DEPLOY_TO_PROD: true
      #     NETLIFY_DEPLOY_MESSAGE: "Prod deploy v${{ github.ref }}"
